version: "3.4"

services:
  ptsapi:
    build:
      context: .
      dockerfile: PTS.API/Dockerfile
    ports:
     - "5201:5201"  # HTTP (host:container)
     - "5202:5202"  # HTTPS (host:container)
    volumes:
     - ./PTS.API/https:/https
    environment:
     - ASPNETCORE_URLS=https://+:5202;http://+:5201
     - ASPNETCORE_HTTPS_PORT=5202
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/neoscoder.pfx
     - ASPNETCORE_Kestrel__Certificates__Default__Password=Farc1lgh#
