// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTS.API.Data;

#nullable disable

namespace PTS.API.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505020830_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PTS.API.Models.Domain.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<int?>("ProductVersionId")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<string>("Tag")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(3);

                    b.Property<int>("TrackingId")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("ProductVersionId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".",
                            Name = "BAKERY",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 2,
                            Description = ".",
                            Name = "BEVERAGE",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 3,
                            Description = ".",
                            Name = "CONDIMENTS",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 4,
                            Description = ".",
                            Name = "CONFECTIONARY",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 5,
                            Description = ".",
                            Name = "DAIRY",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 6,
                            Description = ".",
                            Name = "DRINKING WATER",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 7,
                            Description = ".",
                            Name = "FRUIT DRINK",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 8,
                            Description = ".",
                            Name = "GRAINS",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 9,
                            Description = ".",
                            Name = "MEAT",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 10,
                            Description = ".",
                            Name = "PERSONAL CARE",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 11,
                            Description = ".",
                            Name = "SNACKS",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        });
                });

            modelBuilder.Entity("PTS.API.Models.Domain.CylinderCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CylinderCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".",
                            Name = "BANGLA - SHANGHAI PLATE MAKING LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 2,
                            Description = ".",
                            Name = "DIGITAL ENGRAVERS LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 3,
                            Description = ".",
                            Name = "MASTER PLATE MAKING(BD) CO.LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 4,
                            Description = ".",
                            Name = "PRINTO PACK SYNDICATE",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        });
                });

            modelBuilder.Entity("PTS.API.Models.Domain.PackType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("PackTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".",
                            Name = "BAG",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 2,
                            Description = ".",
                            Name = "BOX",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 3,
                            Description = ".",
                            Name = "BRICK",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 4,
                            Description = ".",
                            Name = "CAN",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 5,
                            Description = ".",
                            Name = "CHASE",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 6,
                            Description = ".",
                            Name = "CLUSTER",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 7,
                            Description = ".",
                            Name = "COMBIFIT",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 8,
                            Description = ".",
                            Name = "CONTAINER",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 9,
                            Description = ".",
                            Name = "CUP",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 10,
                            Description = ".",
                            Name = "FAT CAN",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 11,
                            Description = ".",
                            Name = "FOIL",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 12,
                            Description = ".",
                            Name = "GLASS BOTTLE",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 13,
                            Description = ".",
                            Name = "GLASS JAR",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 14,
                            Description = ".",
                            Name = "MASTER CARTON",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 15,
                            Description = ".",
                            Name = "PET",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 16,
                            Description = ".",
                            Name = "PILLOW",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 17,
                            Description = ".",
                            Name = "PLASTIC JAR",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 18,
                            Description = ".",
                            Name = "POLY",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 19,
                            Description = ".",
                            Name = "POUCH",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 20,
                            Description = ".",
                            Name = "PRISMA",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 21,
                            Description = ".",
                            Name = "SASSY",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 22,
                            Description = ".",
                            Name = "SHRINK",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 23,
                            Description = ".",
                            Name = "STANDING POUCH",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 24,
                            Description = ".",
                            Name = "TIN CONTAINER",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 25,
                            Description = ".",
                            Name = "UHT POUCH",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 26,
                            Description = ".",
                            Name = "WRAPPER",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        });
                });

            modelBuilder.Entity("PTS.API.Models.Domain.PrintingCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PrintingCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".",
                            Name = "AFBL FOOD PARK",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 2,
                            Description = ".",
                            Name = "AKIJ PRINTING & PACKAGES LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 3,
                            Description = ".",
                            Name = "ANNAN PACK LIMITED",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 4,
                            Description = ".",
                            Name = "ARBAB PACK LIMITED",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 5,
                            Description = ".",
                            Name = "BENGAL PRINTING & PACKAGING",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 6,
                            Description = ".",
                            Name = "FRESH PACK INDUSTRIES",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 7,
                            Description = ".",
                            Name = "MAHTAB FLEXIBLE PRINTING PRESS",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 8,
                            Description = ".",
                            Name = "PREMIAFLEX PLASTICS LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 9,
                            Description = ".",
                            Name = "SHAJINAZ EXIM PACK LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        },
                        new
                        {
                            Id = 10,
                            Description = ".",
                            Name = "TAMPACO FOILS LTD",
                            UserId = "e07b4029-5a27-491d-9fc5-7043e22ae5eb"
                        });
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(9);

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int?>("CylinderCompanyId")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<string>("FlavourType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(4);

                    b.Property<int?>("PackTypeId")
                        .HasColumnType("int")
                        .HasColumnOrder(12);

                    b.Property<int?>("PrintingCompanyId")
                        .HasColumnType("int")
                        .HasColumnOrder(11);

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("ProjectDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8);

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(5);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CylinderCompanyId");

                    b.HasIndex("PackTypeId");

                    b.HasIndex("PrintingCompanyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.ProductVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("VersionDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasFilter("[Version] IS NOT NULL");

                    b.ToTable("ProductVersions");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Attachment", b =>
                {
                    b.HasOne("PTS.API.Models.Domain.ProductVersion", "ProductVersion")
                        .WithMany("Attachments")
                        .HasForeignKey("ProductVersionId");

                    b.Navigation("ProductVersion");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Product", b =>
                {
                    b.HasOne("PTS.API.Models.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("PTS.API.Models.Domain.CylinderCompany", "CylinderCompany")
                        .WithMany("Products")
                        .HasForeignKey("CylinderCompanyId");

                    b.HasOne("PTS.API.Models.Domain.PackType", "PackType")
                        .WithMany("Products")
                        .HasForeignKey("PackTypeId");

                    b.HasOne("PTS.API.Models.Domain.PrintingCompany", "PrintingCompany")
                        .WithMany("Products")
                        .HasForeignKey("PrintingCompanyId");

                    b.Navigation("Category");

                    b.Navigation("CylinderCompany");

                    b.Navigation("PackType");

                    b.Navigation("PrintingCompany");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.ProductVersion", b =>
                {
                    b.HasOne("PTS.API.Models.Domain.Product", "Product")
                        .WithMany("ProductVersions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.CylinderCompany", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.PackType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.PrintingCompany", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.Product", b =>
                {
                    b.Navigation("ProductVersions");
                });

            modelBuilder.Entity("PTS.API.Models.Domain.ProductVersion", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
