export interface UpdateProductRequest{
    categoryid?: number,
    packtypeid?: number,
    brand?: string,
    flavourtype?: string,
    origin?: string,
    sku?: string,
    productcode?: string,
    version?: string,
    projectdate?: Date,
    barcode?: string,
    cylindercompanyid?: number,
    printingcompanyid?: number,
    userId?: string,
}